name: Unit tests
on: [pull_request]
jobs:
  run-unit-tests:
    name: Run all the unit tests of this repo
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
