name: Unit tests
on: [push, pull_request]
jobs:
  run-unit-tests:
    name: Run all the unit tests of this repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - run: npm install
      - run: npm test
